- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: copy kernal settings file to local
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/
    force: no

- name: sysctl settings
  shell: 'sysctl -p /etc/sysctl.d/k8s.conf'

- name: load ipvs modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ mod_names }}"
