- name: mkdir docker
  file:
    path: /etc/docker
    state: directory

- name: copy docker daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: install docker-ce
  yum:
    name:
      - docker-ce
      - kubelet
      - kubeadm
      - kubectl
    state: present 

- name: enable docker
  systemd:
    name: docker
    state: started
    enabled: true

- name: enabled kubelet
  systemd:
    name: kubelet
    state: started
    enabled: true
